services:
  app:
    build: ..
    container_name: psec_app
    environment:
      - DB_TYPE=postgres
      - DB_SERVER=db
      - DB_DATABASE=testdb
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpass
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: psec_db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
volumes:
  db_data:
